name:                futhask-metal
version:             0.2.0
git:                 "https://gitlab.com/Gusten_Isfeldt/futhask.git"
license:             BSD3
author:              "Gusten Isfeldt & Miles J. Litteral"
maintainer:          "isfeldt@kth.se"
copyright:           "2020 Gusten Isfeldt"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Generate Haskell wrappers for Futhark libraries
category:            FFI Tools
description:         Please see the README on GitLab at <https://gitlab.com/Gusten_Isfeldt/futhask#futhask>

dependencies:

- directory
- raw-strings-qq
- split
- aeson >= 1.5.6.0
- containers
- text
- unordered-containers
- bytestring

- base >= 4.7 && < 5
- ghc         >= 9.0 && < 9.3
- ghc-source-gen  >= 0.4.2.0
- ghc-paths
- hashable  >= 1.3.5.0
- random   >= 1.2.1
- base-compat
- attoparsec

library:
  source-dirs: src

executables:
  futhask:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futhask-metal
